### ISSUE TITLE
Support for new Rich Text blocks and elements (rich_text_list, rich_text_quote, ...)

### ISSUE THREAD

**Issue by parente** [imryche/blockkit#100]
Is there interest for adding support for https://api.slack.com/reference/block-kit/blocks#rich_text to the blockkit library?

I *might* be able to send a PR for it. Since it's a sizable addition, I wanted to check in first and see if there's support or if someone else is already working on it.

**Comment by imryche** [comment]
Hi! I actually planned to add support for Rich Text Blocks myself, but I'd be more than glad if you could contribute this feature. Please feel free to send a PR!

**Comment by parente** [comment]
@imryche Cool either way. Please don't let me hold you up if you want to work on it. If I find the time and make some headway, I'll drop another comment so we don't duplicate effort.
