### ISSUE TITLE
Context not working with latest release

### ISSUE THREAD

**Issue by palakagrawal22** [imryche/blockkit#105]
For me context and field is not working using blockkit in the version update to latest

**Comment by imryche** [comment]
Please, try the latest release https://github.com/imryche/blockkit/releases/tag/v1.6.2

**Comment by palakagrawal22** [comment]
still the fields are not working error is : The server responded with: {'ok': False, 'error': 'invalid_arguments', 'response_metadata': {'messages': ['[ERROR] failed to match all allowed schemas [json-pointer:/view]', '[ERROR] failed to match all allowed schemas [json-pointer:/view/blocks/4/fields/0]', '[ERROR] must provide an object [json-pointer:/view/blocks/4/fields/0]', '[ERROR] must provide an object [json-pointer:/view/blocks/4/fields/0]', '[ERROR] failed to match all allowed schemas [json-pointer:/view/blocks/4/fields/1]', '[ERROR] must provide an object [json-pointer:/view/blocks/4/fields/1]', '[ERROR] must provide an object [json-pointer:/view/blocks/4/fields/1]', '[ERROR] failed to match all allowed schemas [json-pointer:/view/blocks/5/fields/0]', '[ERROR] must provide an object [json-pointer:/view/blocks/5/fields/0]', '[ERROR] must provide an object [json-pointer:/view/blocks/5/fields/0]', '[ERROR] failed to match all allowed schemas [json-pointer:/view/blocks/5/fields/1]', '[ERROR] must provide an object [json-pointer:/view/blocks/5/fields/1]', '[ERROR] must provide an object [json-pointer:/view/blocks/5/fields/1]']}}
