### ISSUE TITLE
Add attachments to the blockkit

### ISSUE THREAD

**Issue by jldmota** [imryche/blockkit#43]
json example

"attachments": [
		{
			"blocks": [
				{
					"type": "section",
					"text": {
						"type": "mrkdwn",
						"text": "*Alternative hotel options*"
					}
				},
				{
					"type": "section",
					"text": {
						"type": "mrkdwn",
						"text": "<https://example.com|Bates Motel> :star::star:"
					},
					"accessory": {
						"type": "button",
						"text": {
							"type": "plain_text",
							"text": "View",
							"emoji": true
						},
						"value": "view_alternate_1"
					}
				},
				{
					"type": "section",
					"text": {
						"type": "mrkdwn",
						"text": "<https://example.com|The Great Northern Hotel> :star::star::star::star:"
					},
					"accessory": {
						"type": "button",
						"text": {
							"type": "plain_text",
							"text": "View",
							"emoji": true
						},
						"value": "view_alternate_2"
					}
				}
			]
		}
	]
}

**Comment by BenKuhar** [comment]
Would be nice to have this to wrap blocks in a message with the attachments color bar applied.

**Comment by pykenny** [comment]
Unfortunately Slack officials has labeled attachments as [legacy feature](https://api.slack.com/messaging/composing/layouts#when-to-use-attachments), and discourage use of attachments for messaging. (a long message can still be truncated by Slack client in message thread, even when using "pure" block elements in message content, however.)

**Comment by imryche** [comment]
Closing this since attachments are a legacy feature.
