### ISSUE TITLE
black should be an optional dependency

### ISSUE THREAD

**Issue by StefanBrand** [imryche/blockkit#61]
Hi, `black` is listed in the required packages:

https://github.com/imryche/blockkit/blob/master/setup.py#L20

It is being used only in `generators.py`:

https://github.com/imryche/blockkit/blob/master/blockkit/generators.py#L3

I think this is only being used for https://blockkit-generator.com/, right? Therefore I propose to make black an optional dependency.

**Comment by imryche** [comment]
Hi! Good point. Moved `black` to extras in https://github.com/imryche/blockkit/releases/tag/v1.5.2
