### ISSUE TITLE
issue with blockkit generator site

### ISSUE THREAD

**Issue by sumarema** [imryche/blockkit#85]
Hi,
This tool is really good and the site itself sometimes gets cert issues or domain issue, If a Docker image is availble we can host it locally, Please consider that request so we can lauch the tool from a local instance

**Comment by imryche** [comment]
Hey! Sorry for the inconvenience. I've decided to move this tool to a different domain. You can now access it at https://blockkit.botsignals.co

**Comment by sumarema** [comment]
Thank you
